create table if not exists public.league_memberships (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  league_id text not null references public.leagues(id) on delete cascade,
  league_team_id text references public.league_teams(id) on delete set null,
  role text not null default 'admin' check (role in ('admin', 'team_manager')),
  created_at timestamptz not null default now(),

  unique (user_id, league_id)
);

alter table public.league_memberships enable row level security;

create policy "Users can read their own league memberships"
on public.league_memberships
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can create their own league memberships"
on public.league_memberships
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own league memberships"
on public.league_memberships
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own league memberships"
on public.league_memberships
for delete
to authenticated
using (auth.uid() = user_id);
