create table if not exists public.team_rosters (
  id bigint generated by default as identity primary key,
  team_id text not null,
  pokemon_slug text not null,
  slot_number int not null,
  created_at timestamptz not null default now()
);

create unique index if not exists unique_pokemon_owner
on public.team_rosters (pokemon_slug);

create unique index if not exists unique_team_slot
on public.team_rosters (team_id, slot_number);

alter table public.team_rosters enable row level security;

create policy "Anyone can read team rosters"
on public.team_rosters
for select
to anon
using (true);

create policy "Anyone can insert team rosters for demo"
on public.team_rosters
for insert
to anon
with check (true);

create policy "Anyone can update team rosters for demo"
on public.team_rosters
for update
to anon
using (true)
with check (true);

create policy "Anyone can delete team rosters for demo"
on public.team_rosters
for delete
to anon
using (true);
