create table if not exists public.league_matchup_lineups (
  id bigint generated by default as identity primary key,
  league_id text not null references public.leagues(id) on delete cascade,
  matchup_id text not null references public.league_matchups(id) on delete cascade,
  team_id text not null references public.league_teams(id) on delete cascade,
  pokemon_slug text not null,
  slot_number integer not null check (slot_number between 1 and 6),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.league_matchup_lineups
add column if not exists league_id text references public.leagues(id) on delete cascade;

alter table public.league_matchup_lineups
add column if not exists matchup_id text references public.league_matchups(id) on delete cascade;

alter table public.league_matchup_lineups
add column if not exists team_id text references public.league_teams(id) on delete cascade;

alter table public.league_matchup_lineups
add column if not exists pokemon_slug text;

alter table public.league_matchup_lineups
add column if not exists slot_number integer;

alter table public.league_matchup_lineups
add column if not exists created_at timestamptz not null default now();

alter table public.league_matchup_lineups
add column if not exists updated_at timestamptz not null default now();

create unique index if not exists league_matchup_lineups_unique_slot
on public.league_matchup_lineups (league_id, matchup_id, team_id, slot_number);

create unique index if not exists league_matchup_lineups_unique_pokemon
on public.league_matchup_lineups (league_id, matchup_id, team_id, pokemon_slug);

create index if not exists league_matchup_lineups_usage_idx
on public.league_matchup_lineups (league_id, team_id, pokemon_slug);

alter table public.league_matchup_lineups enable row level security;

grant select, insert, update, delete on public.league_matchup_lineups to authenticated;

do $$
begin
  if to_regclass('public.league_matchup_lineups_id_seq') is not null then
    grant usage, select on sequence public.league_matchup_lineups_id_seq to authenticated;
  end if;
end $$;

create or replace function public.get_matchup_lineup_status(
  target_league_id text,
  target_matchup_id text
)
returns table(team_id text, selected_count bigint)
language sql
security definer
set search_path = public
as $$
  select lineup.team_id, count(*)::bigint as selected_count
  from public.league_matchup_lineups as lineup
  where lineup.league_id = target_league_id
    and lineup.matchup_id = target_matchup_id
    and exists (
      select 1
      from public.league_memberships as membership
      where membership.league_id = target_league_id
        and membership.user_id = auth.uid()
    )
  group by lineup.team_id;
$$;

create or replace function public.can_read_matchup_lineup(
  target_league_id text,
  target_matchup_id text,
  target_team_id text
)
returns boolean
language sql
security definer
set search_path = public
as $$
  with membership as (
    select league_team_id
    from public.league_memberships
    where league_id = target_league_id
      and user_id = auth.uid()
    limit 1
  ),
  lineup_counts as (
    select team_id, count(*)::integer as selected_count
    from public.league_matchup_lineups
    where league_id = target_league_id
      and matchup_id = target_matchup_id
    group by team_id
  ),
  reveal_ready as (
    select coalesce(count(*) = 2 and bool_and(selected_count >= 6), false) as is_ready
    from lineup_counts
  )
  select exists (select 1 from membership)
    and (
      exists (select 1 from membership where league_team_id = target_team_id)
      or exists (select 1 from reveal_ready where is_ready)
    );
$$;

grant execute on function public.get_matchup_lineup_status(text, text) to authenticated;
grant execute on function public.can_read_matchup_lineup(text, text, text) to authenticated;

drop policy if exists "Authenticated users can read lineups" on public.league_matchup_lineups;
drop policy if exists "Authenticated users can create lineups" on public.league_matchup_lineups;
drop policy if exists "Authenticated users can update lineups" on public.league_matchup_lineups;
drop policy if exists "Authenticated users can delete lineups" on public.league_matchup_lineups;
drop policy if exists "Members can read own or revealed matchup lineups" on public.league_matchup_lineups;
drop policy if exists "Members can insert own matchup lineups" on public.league_matchup_lineups;
drop policy if exists "Members can update own matchup lineups" on public.league_matchup_lineups;
drop policy if exists "Members can delete own matchup lineups" on public.league_matchup_lineups;

create policy "Members can read own or revealed matchup lineups"
on public.league_matchup_lineups
for select
to authenticated
using (
  public.can_read_matchup_lineup(league_id, matchup_id, team_id)
);

create policy "Members can insert own matchup lineups"
on public.league_matchup_lineups
for insert
to authenticated
with check (
  exists (
    select 1
    from public.league_memberships as membership
    where membership.league_id = league_matchup_lineups.league_id
      and membership.user_id = auth.uid()
      and membership.league_team_id = league_matchup_lineups.team_id
  )
);

create policy "Members can update own matchup lineups"
on public.league_matchup_lineups
for update
to authenticated
using (
  exists (
    select 1
    from public.league_memberships as membership
    where membership.league_id = league_matchup_lineups.league_id
      and membership.user_id = auth.uid()
      and membership.league_team_id = league_matchup_lineups.team_id
  )
)
with check (
  exists (
    select 1
    from public.league_memberships as membership
    where membership.league_id = league_matchup_lineups.league_id
      and membership.user_id = auth.uid()
      and membership.league_team_id = league_matchup_lineups.team_id
  )
);

create policy "Members can delete own matchup lineups"
on public.league_matchup_lineups
for delete
to authenticated
using (
  exists (
    select 1
    from public.league_memberships as membership
    where membership.league_id = league_matchup_lineups.league_id
      and membership.user_id = auth.uid()
      and membership.league_team_id = league_matchup_lineups.team_id
  )
);
