create table if not exists public.league_draft_picks (
  id bigint generated by default as identity primary key,
  league_id text not null references public.leagues(id) on delete cascade,
  league_team_id text not null references public.league_teams(id) on delete cascade,
  overall_pick int not null,
  round_number int not null,
  pick_in_round int not null,
  pokemon_slug text not null,
  created_at timestamptz not null default now(),

  unique (league_id, overall_pick),
  unique (league_id, pokemon_slug)
);

alter table public.league_draft_picks enable row level security;

drop policy if exists "Authenticated users can read draft picks" on public.league_draft_picks;
drop policy if exists "Authenticated users can create draft picks" on public.league_draft_picks;
drop policy if exists "Authenticated users can delete draft picks" on public.league_draft_picks;

create policy "Authenticated users can read draft picks"
on public.league_draft_picks
for select
to authenticated
using (true);

create policy "Authenticated users can create draft picks"
on public.league_draft_picks
for insert
to authenticated
with check (true);

create policy "Authenticated users can delete draft picks"
on public.league_draft_picks
for delete
to authenticated
using (true);

drop policy if exists "Authenticated users can read team rosters" on public.team_rosters;
drop policy if exists "Authenticated users can create team rosters" on public.team_rosters;
drop policy if exists "Authenticated users can delete team rosters" on public.team_rosters;

create policy "Authenticated users can read team rosters"
on public.team_rosters
for select
to authenticated
using (true);

create policy "Authenticated users can create team rosters"
on public.team_rosters
for insert
to authenticated
with check (true);

create policy "Authenticated users can delete team rosters"
on public.team_rosters
for delete
to authenticated
using (true);
