create table if not exists public.draft_picks (
  id bigint generated by default as identity primary key,
  overall_pick int not null unique,
  round_number int not null,
  pick_in_round int not null,
  team_id text not null,
  pokemon_slug text not null unique,
  created_at timestamptz not null default now()
);

alter table public.draft_picks enable row level security;

create policy "Anyone can read draft picks"
on public.draft_picks
for select
to anon
using (true);

create policy "Anyone can insert draft picks for demo"
on public.draft_picks
for insert
to anon
with check (true);

create policy "Anyone can update draft picks for demo"
on public.draft_picks
for update
to anon
using (true)
with check (true);

create policy "Anyone can delete draft picks for demo"
on public.draft_picks
for delete
to anon
using (true);
