create table if not exists public.league_draft_order (
  id bigint generated by default as identity primary key,
  league_id text not null references public.leagues(id) on delete cascade,
  slot_number int not null,
  league_team_id text not null references public.league_teams(id) on delete cascade,
  created_at timestamptz not null default now(),

  unique (league_id, slot_number),
  unique (league_id, league_team_id)
);

create table if not exists public.league_draft_state (
  league_id text primary key references public.leagues(id) on delete cascade,
  is_started boolean not null default false,
  is_paused boolean not null default true,
  current_pick_started_at timestamptz,
  updated_at timestamptz not null default now()
);

alter table public.league_draft_order enable row level security;
alter table public.league_draft_state enable row level security;

drop policy if exists "Authenticated users can read draft order" on public.league_draft_order;
drop policy if exists "Authenticated users can create draft order" on public.league_draft_order;
drop policy if exists "Authenticated users can update draft order" on public.league_draft_order;
drop policy if exists "Authenticated users can delete draft order" on public.league_draft_order;

create policy "Authenticated users can read draft order"
on public.league_draft_order
for select
to authenticated
using (true);

create policy "Authenticated users can create draft order"
on public.league_draft_order
for insert
to authenticated
with check (true);

create policy "Authenticated users can update draft order"
on public.league_draft_order
for update
to authenticated
using (true)
with check (true);

create policy "Authenticated users can delete draft order"
on public.league_draft_order
for delete
to authenticated
using (true);

drop policy if exists "Authenticated users can read draft state" on public.league_draft_state;
drop policy if exists "Authenticated users can create draft state" on public.league_draft_state;
drop policy if exists "Authenticated users can update draft state" on public.league_draft_state;

create policy "Authenticated users can read draft state"
on public.league_draft_state
for select
to authenticated
using (true);

create policy "Authenticated users can create draft state"
on public.league_draft_state
for insert
to authenticated
with check (true);

create policy "Authenticated users can update draft state"
on public.league_draft_state
for update
to authenticated
using (true)
with check (true);

alter table public.team_rosters
add column if not exists league_id text references public.leagues(id) on delete cascade;

update public.team_rosters
set league_id = public.league_teams.league_id
from public.league_teams
where public.team_rosters.team_id = public.league_teams.id
and public.team_rosters.league_id is null;

drop index if exists unique_pokemon_owner;

create unique index if not exists unique_league_pokemon_owner
on public.team_rosters (league_id, pokemon_slug)
where league_id is not null;
