create table if not exists public.flash_family_trades (
  id bigint generated by default as identity primary key,
  league_id text not null references public.leagues(id) on delete cascade,
  week integer not null check (week between 0 and 52),
  sender_team_id text not null,
  receiver_team_id text not null,
  sender_pokemon_slugs text[] not null,
  receiver_pokemon_slugs text[] not null,
  sender_resulting_points integer not null check (sender_resulting_points >= 0),
  receiver_resulting_points integer not null check (receiver_resulting_points >= 0),
  status text not null default 'pending' check (status in ('pending', 'accepted', 'declined', 'cancelled')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  accepted_at timestamptz,
  check (sender_team_id <> receiver_team_id),
  check (cardinality(sender_pokemon_slugs) between 1 and 2),
  check (cardinality(receiver_pokemon_slugs) between 1 and 2)
);

create index if not exists flash_family_trades_participants_idx
on public.flash_family_trades (league_id, week, sender_team_id, receiver_team_id, status);

alter table public.flash_family_trades enable row level security;

create or replace function public.read_flash_family_trades(p_access_code text)
returns setof public.flash_family_trades
language sql
security definer
set search_path = public
as $$
  select trades.*
  from public.flash_family_trades as trades
  where trades.league_id = 'flash-family-season-1'
    and (
      trades.sender_team_id = case upper(trim(coalesce(p_access_code, '')))
        when 'PUFF1' then 'boston-eeltics'
        when 'NETO' then 'miami-dragapults'
        when 'MOON4' then 'massachusetts-midnight'
        when 'FORMIDABLE' then 'sunnyshore-city-shelter'
        when 'NC50' then 'north-carolina-ceruledge'
        else null
      end
      or trades.receiver_team_id = case upper(trim(coalesce(p_access_code, '')))
        when 'PUFF1' then 'boston-eeltics'
        when 'NETO' then 'miami-dragapults'
        when 'MOON4' then 'massachusetts-midnight'
        when 'FORMIDABLE' then 'sunnyshore-city-shelter'
        when 'NC50' then 'north-carolina-ceruledge'
        else null
      end
    )
  order by trades.created_at desc;
$$;

create or replace function public.propose_flash_family_trade(
  p_access_code text,
  p_receiver_team_id text,
  p_sender_pokemon_slugs text[],
  p_receiver_pokemon_slugs text[],
  p_sender_resulting_points integer,
  p_receiver_resulting_points integer
)
returns bigint
language plpgsql
security definer
set search_path = public
as $$
declare
  league_key constant text := 'flash-family-season-1';
  allowed_teams constant text[] := array[
    'daytona-torterras', 'kansas-krooks', 'south-jersey-hounds', 'chicago-conkquerers',
    'las-vegas-gatrs', 'north-carolina-ceruledge', 'uconn-arcanines', 'boston-eeltics',
    'sunnyshore-city-shelter', 'massachusetts-midnight', 'miami-dragapults',
    'san-francisco-soulfire', 'stockholm-spin-cycles', 'dallas-disguises'
  ];
  sender_team text;
  sender_slugs text[];
  receiver_slugs text[];
  active_week integer;
  point_cap integer;
  trade_id bigint;
begin
  sender_team := case upper(trim(coalesce(p_access_code, '')))
    when 'PUFF1' then 'boston-eeltics'
    when 'NETO' then 'miami-dragapults'
    when 'MOON4' then 'massachusetts-midnight'
    when 'FORMIDABLE' then 'sunnyshore-city-shelter'
    when 'NC50' then 'north-carolina-ceruledge'
    else null
  end;

  if sender_team is null then raise exception 'Sign in with a league access code to propose a trade'; end if;
  if p_receiver_team_id = sender_team or not (p_receiver_team_id = any(allowed_teams)) then
    raise exception 'Choose another league team';
  end if;

  select array_agg(distinct lower(trim(slug)) order by lower(trim(slug)))
  into sender_slugs from unnest(coalesce(p_sender_pokemon_slugs, array[]::text[])) as picks(slug);
  select array_agg(distinct lower(trim(slug)) order by lower(trim(slug)))
  into receiver_slugs from unnest(coalesce(p_receiver_pokemon_slugs, array[]::text[])) as picks(slug);

  if cardinality(coalesce(sender_slugs, array[]::text[])) not between 1 and 2
    or cardinality(coalesce(receiver_slugs, array[]::text[])) not between 1 and 2 then
    raise exception 'Choose one or two Pokemon from each team';
  end if;

  select coalesce(current_matchup_number, 0), roster_point_cap
  into active_week, point_cap
  from public.leagues where id = league_key;

  if p_sender_resulting_points not between 0 and point_cap
    or p_receiver_resulting_points not between 0 and point_cap then
    raise exception 'Both rosters must fit under the league point cap';
  end if;

  if exists (
    select 1 from public.flash_family_trades
    where league_id = league_key and week = active_week and status = 'accepted'
      and (sender_team_id in (sender_team, p_receiver_team_id) or receiver_team_id in (sender_team, p_receiver_team_id))
  ) then raise exception 'One of these teams has already completed its trade for this week'; end if;

  if (select count(*) from public.team_rosters where league_id = league_key and team_id = sender_team and pokemon_slug = any(sender_slugs)) <> cardinality(sender_slugs)
    or (select count(*) from public.team_rosters where league_id = league_key and team_id = p_receiver_team_id and pokemon_slug = any(receiver_slugs)) <> cardinality(receiver_slugs) then
    raise exception 'A selected Pokemon is no longer on that roster';
  end if;

  insert into public.flash_family_trades (
    league_id, week, sender_team_id, receiver_team_id,
    sender_pokemon_slugs, receiver_pokemon_slugs,
    sender_resulting_points, receiver_resulting_points
  ) values (
    league_key, active_week, sender_team, p_receiver_team_id,
    sender_slugs, receiver_slugs,
    p_sender_resulting_points, p_receiver_resulting_points
  ) returning id into trade_id;

  return trade_id;
end;
$$;

create or replace function public.respond_flash_family_trade(
  p_access_code text,
  p_trade_id bigint,
  p_action text
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  league_key constant text := 'flash-family-season-1';
  manager_team text;
  active_week integer;
  roster_cap integer;
  trade_row public.flash_family_trades%rowtype;
  sender_roster text[];
  receiver_roster text[];
  new_sender_roster text[];
  new_receiver_roster text[];
begin
  manager_team := case upper(trim(coalesce(p_access_code, '')))
    when 'PUFF1' then 'boston-eeltics'
    when 'NETO' then 'miami-dragapults'
    when 'MOON4' then 'massachusetts-midnight'
    when 'FORMIDABLE' then 'sunnyshore-city-shelter'
    when 'NC50' then 'north-carolina-ceruledge'
    else null
  end;
  if manager_team is null then raise exception 'Sign in with a league access code'; end if;

  select * into trade_row
  from public.flash_family_trades
  where id = p_trade_id and league_id = league_key and status = 'pending'
  for update;
  if not found then raise exception 'This trade is no longer pending'; end if;

  if lower(coalesce(p_action, '')) = 'cancel' then
    if manager_team <> trade_row.sender_team_id then raise exception 'Only the sender can cancel this trade'; end if;
    update public.flash_family_trades set status = 'cancelled', updated_at = now() where id = p_trade_id;
    return;
  end if;

  if manager_team <> trade_row.receiver_team_id then raise exception 'Only the receiving manager can respond to this trade'; end if;
  if lower(coalesce(p_action, '')) = 'decline' then
    update public.flash_family_trades set status = 'declined', updated_at = now() where id = p_trade_id;
    return;
  end if;
  if lower(coalesce(p_action, '')) <> 'accept' then raise exception 'Choose accept, decline, or cancel'; end if;

  select coalesce(current_matchup_number, 0), roster_point_cap
  into active_week, roster_cap from public.leagues where id = league_key for update;
  if trade_row.week <> active_week then raise exception 'Trades can only be accepted during the week they were proposed'; end if;
  if trade_row.sender_resulting_points > roster_cap or trade_row.receiver_resulting_points > roster_cap then
    raise exception 'This trade no longer fits under the league point cap';
  end if;
  if exists (
    select 1 from public.flash_family_trades
    where league_id = league_key and week = active_week and status = 'accepted'
      and id <> p_trade_id
      and (sender_team_id in (trade_row.sender_team_id, trade_row.receiver_team_id)
        or receiver_team_id in (trade_row.sender_team_id, trade_row.receiver_team_id))
  ) then raise exception 'One of these teams has already completed its trade for this week'; end if;

  perform 1 from public.team_rosters
  where league_id = league_key and team_id in (trade_row.sender_team_id, trade_row.receiver_team_id)
  for update;

  if (select count(*) from public.team_rosters where league_id = league_key and team_id = trade_row.sender_team_id and pokemon_slug = any(trade_row.sender_pokemon_slugs)) <> cardinality(trade_row.sender_pokemon_slugs)
    or (select count(*) from public.team_rosters where league_id = league_key and team_id = trade_row.receiver_team_id and pokemon_slug = any(trade_row.receiver_pokemon_slugs)) <> cardinality(trade_row.receiver_pokemon_slugs) then
    raise exception 'A selected Pokemon is no longer on that roster';
  end if;

  select coalesce(array_agg(pokemon_slug order by slot_number), array[]::text[])
  into sender_roster from public.team_rosters where league_id = league_key and team_id = trade_row.sender_team_id;
  select coalesce(array_agg(pokemon_slug order by slot_number), array[]::text[])
  into receiver_roster from public.team_rosters where league_id = league_key and team_id = trade_row.receiver_team_id;

  select coalesce(array_agg(slug order by position), array[]::text[]) into new_sender_roster
  from unnest(sender_roster) with ordinality as roster(slug, position)
  where not (slug = any(trade_row.sender_pokemon_slugs));
  new_sender_roster := new_sender_roster || trade_row.receiver_pokemon_slugs;

  select coalesce(array_agg(slug order by position), array[]::text[]) into new_receiver_roster
  from unnest(receiver_roster) with ordinality as roster(slug, position)
  where not (slug = any(trade_row.receiver_pokemon_slugs));
  new_receiver_roster := new_receiver_roster || trade_row.sender_pokemon_slugs;

  select roster_pokemon_cap into roster_cap from public.leagues where id = league_key;
  if cardinality(new_sender_roster) > roster_cap or cardinality(new_receiver_roster) > roster_cap then
    raise exception 'This trade would exceed the roster size limit';
  end if;

  delete from public.team_rosters
  where league_id = league_key and team_id in (trade_row.sender_team_id, trade_row.receiver_team_id);
  insert into public.team_rosters (league_id, team_id, pokemon_slug, slot_number)
  select league_key, trade_row.sender_team_id, slug, position::integer
  from unnest(new_sender_roster) with ordinality as roster(slug, position);
  insert into public.team_rosters (league_id, team_id, pokemon_slug, slot_number)
  select league_key, trade_row.receiver_team_id, slug, position::integer
  from unnest(new_receiver_roster) with ordinality as roster(slug, position);

  update public.flash_family_trades set status = 'accepted', accepted_at = now(), updated_at = now() where id = p_trade_id;
  update public.flash_family_trades set status = 'cancelled', updated_at = now()
  where league_id = league_key and week = active_week and status = 'pending' and id <> p_trade_id
    and (sender_team_id in (trade_row.sender_team_id, trade_row.receiver_team_id)
      or receiver_team_id in (trade_row.sender_team_id, trade_row.receiver_team_id));
end;
$$;

revoke all on function public.read_flash_family_trades(text) from public;
revoke all on function public.propose_flash_family_trade(text, text, text[], text[], integer, integer) from public;
revoke all on function public.respond_flash_family_trade(text, bigint, text) from public;
grant execute on function public.read_flash_family_trades(text) to anon, authenticated;
grant execute on function public.propose_flash_family_trade(text, text, text[], text[], integer, integer) to anon, authenticated;
grant execute on function public.respond_flash_family_trade(text, bigint, text) to anon, authenticated;
